### ISSUE TITLE
Pb d'insertion d'un établissement dans Moodle

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/ESCOSynchroMoodle#3]
Bonjour,
nous avons fait tourner le script pour qu'il insère un novuel établissement et rencontrons des problèmes : la catégorie n'apparaît pas dans la liste des catégories Moodle de premier niveau (les établissements). Pourtant elle est bien dans la table course_categories.
Les requêtes d'insertion dans la base sont-elle bien les mêmes que dans la version python 2 ?
Vous arrivez à bien voir un nouvel établissement dans la liste des catégories : /course/management.php ?
Est-ce que cela a à voir avec la création du cours zone privée dans cette catégorie qui se serait mal passée ?

Nous ne voyons pas d'où provient le problème....

Merci de vos lumières.
Christian Daviau.

**Comment by vcastro45** [comment]
Bonjour,
Je vous prie de bien vouloir excuser le délai de réponse, j'étais absent une partie de la semaine dernière.

J'arrive effectivement au même constat que vous: L'insertion est présente dans la base de données mais invisible dans l'IHM.
Nous n'avons normalement pas touché les fonctions d'insertion du script python 2 mais il est possible qu'il y ait eu des effets de bords lors de la ré-organisation/clarification du code.
Je me penche sur le problème tout de suite et je vous tiens au courant dès que j'ai du nouveau.

**Comment by vcastro45** [comment]
Je viens d'identifier une curiosité au niveau de l'IHM moodle:

sur la page des catégories, la nouvelle catégorie n'est pas visible.
Si on choisi de trier par "all categories", la nouvelle catégorie apparait (l'url devient `/course/management.php?categoryid=1106`).
Si on revient sur `/course/management.php`, la nouvelle catégorie est de nouveau visible.
Peut-être est-ce dû à un cache au niveau de Moodle ?

La seule différence dans la base de donnée après l'application du tri, c'est la revalorisation du champ `sortorder` (initialement défini à 999) à 740000.
Mais si on remet le champ à 999 à la main, la catégorie reste visible dans l'IHM, ce qui me conforte dans l'idée qu'un cache est rafraîchi lorsque l'on applique un tri.

En tous cas, il y a fort à parier que ce "problème" existait déjà avec l'ancien script.

**Comment by vcastro45** [comment]
Après approfondissement, c'est effectivement un problème de cache.
Un problème de "Sessions cache" précisément.
Le seul moyen de résoudre ce problème est de vider ce cache. Malheureusement, ce n'est pas possible depuis un webservice moodle.

Il faut donc soit le faire manuellement dans l'IHM de moodle (Site administration > Plugins > Caching > Configuration > Purger le cache "Course categories lists for particular user")

Soit via le CLI Moodle (ce qui pourrait vous permettre de l'automatiser) avec les commandes:
```bash
$ php admin/cli/kill_all_sessions.php
$ php admin/cli/purge_caches.php
```
Il est aussi possible que suite à cela l'IHM Moodle affiche un message d'erreur. C'est car Moodle n'arrive plus à écrire dans le dossier `moodledata`, il faut soit lui redonner les droits après chaque purge, soit configurer votre serveur en conséquence.
