### ISSUE TITLE
Nom remplacer par le prénom

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroMoodle#4]
Bonjour,

Un bug impossible à voir avec notre anonymisation où les noms ont été remplacer par les prénoms.

Le fait est que a l'insertion d'un utilisateur le nom (last_name) est alimenté par le prénom (given_name).

Dans synchronizer.py line 250 par exemple  2 fois given_name:

`self.__db.insert_moodle_user(eleve_ldap.uid, eleve_ldap.given_name,
                                         eleve_ldap.given_name, eleve_ldap.mail,
                                         mail_display, etablissement_context.etablissement_theme)
`

Peut être aussi  à d'autres endroits.

**Comment by vcastro45** [comment]
Effectivement, vous avez raison: le prénom était mis à la place du nom à plusieurs endroits.
