### ISSUE TITLE
Cohorte de classe non associe à l'établissement

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroMoodle#5]
A la création d'une cohorte liée à la classe d'un élève,  celle-ci n'est pas associé à la bonne catégorie (correspondant à l'établissement)
dans la base le contextid=1

**Comment by vcastro45** [comment]
Bonjour.
Dans quel cas précis cela arrive ?
Je n'arrive pas à reproduire le cas.

**Comment by cdaviau** [comment]
Nous avons relevé le problème lors de la création d'un établissement. Les cohortes qui auraient dû lui être associées étaient en fait associées à la catégorie 1 et non à la catégorie du nouvel établissement.

**Comment by vcastro45** [comment]
Bonjour,
Nos tests unitaires partent toujours d'une BDD vide. Chaque établissement est donc un nouvel établissement et pourtant je n'ai pas de problème à priori.
Pouvez-vous être plus précis svp ?
De quelle table parlez-vous lorsque vous parlez du contextid=1 ?
Pouvez-vous me transmettre les données LDAP de l'établissement et d'un utilisateur concerné ?

**Comment by plegay** [comment]
Dans la table mdl_cohort,
Il y a pleins de cohortes  créées avec le contextId = 1
Ce qui fait (si j'ai bien compris) qu'elles sont rattachées à aucun établissement.
Dans l'interface ça se traduit qu'elles sont visibles dans la page 
"Système : cohortes disponibles"
alors que l'on ne devrait rien avoir à cet endroit.

(l'accès a la page : Administration du site -> Fonctions avancées -> Utilisateurs -> Cohortes)

Après avoir mieux regardé il semble que les cohortes soit aussi associées a la catégorie de l'établissement.

Je pense que toutes Les cohortes sont concernées (j'en ai 50):
Profs de l'établissement...
Profs de la Classe...
Élèves de la Classe...
Élèves du Niveau de formation ...

**Comment by plegay** [comment]
Pour mieux comprendre, je viens d'ajouter un nouvel établissement, et je n'ai pas eu ce problème 
Ca vient peut-être d'une realease plus ancienne, ou d'un autre passage de la synchro??
Je vais chercher à le reproduire.

**Comment by vcastro45** [comment]
Il n'existe pas de règle de gestion particulière dans le synchroniseur qui définisse qu'un contextId à 1 ne soit rattaché à aucun établissement.
Est-ce seulement le cas dans l'IHM de Moodle ?
Comme je l'ai dit plus haut, nos tests partent toujours d'une BDD vide, et je n'ai encore recensé aucun cas où tous les contextId seraient à 1.

Je pense que le problème est plus fin que cela.

**Comment by cdaviau** [comment]
Bonjour,
à vous lire, j'ai peur qu'il y ait des éléments peu clairs. Je les explicite, et excusez moi si c'est inutile.

Le contextId 1 correspond au premier niveau des catégories, le niveau système, au dessus des catégories des établissements. Toutes les catégories correspondantes aux établissements sont sous la catégorie de contextId = 1.
Toutes les catégories ne sont pas forcément un établissement. On pourrait créer des catégories sans rapport avec les établissements. Par exemple une catégorie disciplinaire mathématique dans laquelle on mettrait des cours pour des profs de math.

**Comment by vcastro45** [comment]
@cdaviau Vos explications sont belles et bien utiles mais je ne pense pas qu'elles me permettrons d'avancer sur le sujet.
En effet, du point de vue du code, nous n'attachons pas d’intérêt particulier à tel ou tel contextId: Le programme récupère seulement le contextId de la catégorie de l'établissement concerné en BDD et à la cohorte de classe cible. 

A moins qu'il n'y ai une erreur dans le code qui soit encore non-identifiée (ce qui n'est pas impossible bien-sur), je pense qu'il se peut que la BDD que vous utilisez présente des erreurs plus en amont, au niveau des contextid des établissements, ou des niveaux de contextes.

**Comment by cdaviau** [comment]
Je doute que ce soit un souci dans la BDD, car si c'est le cas, je pense que nous nous en serions apperçu ou qu'un établissement nous l'aurait signalé...
Dans notre BDD, aucune cohorte n'est associée à la catégorie 1 et nous avons bien une catégorie de niveau 2 associée à chaque établissement que nous servons.
