### ISSUE TITLE
problèmes de creation de cohorte

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroMoodle#6]
J'ouvre une deuxième issue car je ne sais pas s'il y a un rapport avec la précédente

Ce problème est mieux identifié:
À  la création d'un nouvel établissement :
avec un enseignants (F1700k17) qui est  dans 2 établissements (données ldap) :
`
escouai=0291595B => CLG-DE L'IROISE-ac-RENNES => siren=19291595700018
escouai=0290009C => LG-DE L'IROISE-ac-RENNES 19290009000015 
`
avec des classes dans le lycée (LG..) par exemple: 
`
ENTAusEnsCleasses = ENTStructureSIREN=19290009000015,ou=structures,dc=esco-centre,dc=fr$TS1
`
La synchro va créer une cohorte dans le collège (le log):
`
[2019-05-06 11:49:09,463] [INFO] [etablissement.0291595B.enseignant.F1700k17] Inscription de l'enseignant uid=F1700k17, given_name=Pauline, sn=SANCHEZ dans les cohortes de classes ['2NDE1', '1ERE S1', 'TES2', '2NDE3', '1ERE S2', 'TS2', '1ERE L', '2NDE8', '1ERE S4', 'TES1', '2NDE7', '2NDE6', '1ERE ES2', 'TES3', '1ERE ES3', 'TS3', 'TS1', '2NDE2', '2NDE4', '2NDE5', '1ERE S3', 'TL', '1ERE ES1']

...

[2019-05-06 11:49:09,500] [INFO] [etablissement.0291595B.enseignant.F1700k17] Creation de la cohorte (name=Profs de la Classe TS1)

...
`

**Comment by vcastro45** [comment]
Si je comprend bien, le problème est que la synchro enregistre l'enseignant dans les classe de lycées dans le collège ? (et inversement ??)

Est-il possible d'avoir l'export des données dudit enseignants dans le LDAP (anonymisées) afin que je puisse reproduire le cas de mon côté ?

**Comment by plegay** [comment]
En resumé quand j'ai ajouter le collége dans la liste des étabs à traiter. 
Un  profs du collège ayant des cours dans le lycée a provoqué la création de cohortes dans le collège avec le nom des classes du lycée. exemple  Profs de la Classe TS1 avec comme seul membre l'enseignant lui-même. 
Ça m'ennuie un peu de vous donner mes jeux de test car, 
car si on teste sur les mêmes données on diminue l'exhaustivité des tests. Et faire le travail en doublons n'est pas très utile.
Pour reproduire le problème il devrait suffire d'ajouter à un enseignant des cours dans un autre établissement.

**Comment by plegay** [comment]
si ça peut aider je joins les logs 
sachant que l'uai du collège vaut 0291595B celle du lycee = 0290009C
et que les classes 2NDE.. 1ERE.. et T.. sont toutes du lycées
voir les lignes de creation de cohorte dans le college: 4530 à 4552 
[synchromoodle.log](https://github.com/GIP-RECIA/ESCOSynchroMoodle/files/3148069/synchromoodle.log)
